-- Reference shape for generated project modulefiles.
-- Actual files are generated from project.toml under the XDG cache.
help("Generated project environment")
whatis("Generated by proj")
family("project")

-- depends_on("compiler/version")
-- setenv("PROJ_ACTIVE", "name")
-- prepend_path("PATH", "/project/root/bin")
-- set_alias("helper", "command")
