from __future__ import annotations

import hashlib
import json
from pathlib import Path

from .config import Config
from .metadata import MODULE_CATEGORIES, Project


def _lua(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(project: Project) -> str:
    dependencies = [
        module
        for category in MODULE_CATEGORIES
        for module in project.modules.get(category, ())
    ]
    lines = [
        "-- Generated by proj. Do not edit.",
        f"-- source: {project.metadata_path}",
        f"help({_lua(project.description)})",
        f"whatis({_lua('Name: ' + project.name)})",
        f"whatis({_lua('Description: ' + project.description)})",
        'family("project")',
    ]
    for dependency in dependencies:
        lines.append(f"depends_on({_lua(dependency)})")
    lines.extend(
        [
            f"setenv(\"PROJ_ACTIVE\", {_lua(project.name)})",
            f"setenv(\"PROJ_ROOT\", {_lua(str(project.root))})",
            f"setenv(\"PROJ_METADATA\", {_lua(str(project.metadata_path))})",
            f"setenv(\"PROJ_MODULE\", {_lua(project.module_name)})",
        ]
    )
    if project.python_environment:
        lines.append(
            f"setenv(\"PROJ_MAMBA_ENV\", {_lua(project.python_environment)})"
        )
    for key, value in sorted(project.environment.items()):
        lines.append(f"setenv({_lua(key)}, {_lua(project.expand(value))})")
    for value in project.prepend_paths:
        lines.append(f"prepend_path(\"PATH\", {_lua(project.expand(value))})")
    for key, value in sorted(project.aliases.items()):
        lines.append(f"set_alias({_lua(key)}, {_lua(project.expand(value))})")
    lines.append("")
    return "\n".join(lines)


def materialize(config: Config, project: Project) -> tuple[Path, bool]:
    output = config.module_cache / "project" / f"{project.name}.lua"
    content = render(project)
    digest = hashlib.sha256(content.encode()).hexdigest()
    digest_file = output.with_suffix(".sha256")
    current = digest_file.read_text().strip() if digest_file.is_file() else ""
    if output.is_file() and current == digest:
        return output, False
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(".lua.tmp")
    temporary.write_text(content)
    temporary.replace(output)
    digest_file.write_text(digest + "\n")
    return output, True
